### ISSUE TITLE
I found a error after run `flutter build web`

### ISSUE THREAD

**Issue by pool13433** [anoochit/zeal_iot#11]
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile
js' instead.
lib/main.dart:8:8:
Error: Error when reading 'lib/firebase_options.dart': Error reading 'lib/firebase_options.dart'  (No such file or
directory)
import 'package:zweb/firebase_options.dart';
       ^
lib/main.dart:17:14:
Error: Undefined name 'DefaultFirebaseOptions'.
    options: DefaultFirebaseOptions.currentPlatform,
             ^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

*** **I saw that the missing file was ignored by git.**

**Comment by anoochit** [comment]
Config Firebase using "flutterfirecli"  and try again, see [document](https://github.com/anoochit/zeal_iot/blob/master/doc/index.md)

**Comment by pool13433** [comment]
completed. thanks
